# Generated by Django 3.1.7 on 2021-03-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('prep_time_min', models.IntegerField()),
                ('cook_time_min', models.IntegerField()),
                ('yields', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', models.JSONField(blank=True)),
                ('steps', models.JSONField(blank=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restourant.category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogAndPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('creator', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('short_description', models.CharField(max_length=500)),
                ('blog_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restourant.blogcategory')),
            ],
        ),
    ]
