# Generated by Django 3.1.7 on 2021-03-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restourant', '0002_auto_20210317_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='recipe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restourant.recipes'),
        ),
    ]
